export const ATTEMPTS_COUNT = 6;

export const ALPHABET_LETTERS = new Set('abcdefghijklmnopqrstuvwxyz');

export const WORDS = [
    'forest',
    'desert',
    'island',
    'jungle',
    'breeze',
    'turtle',
    'beetle',
    'monkey',
    'gopher',
    'iguana',
    'salmon',
    'falcon',
    'donkey',
    'shrimp',
    'planet',
    'galaxy',
    'meteor',
    'rocket',
    'cosmic',
    'saturn',
    'pickle',
    'bottle',
    'tomato',
    'fossil',
    'guitar',
    'bridge',
    'tunnel',
    'magnet',
    'helmet',
    'jacket',
    'alicia',
    'hanyan',
    'lukian',
    'maksym',
    'enough',
    'legend',
    'common',
    'maniac',
];
